### Numerical Computing With Numpy

The Numpy library provides specialized data structures, functions, and other tools for numerical computing in Python

In [4]:
import numpy as np

Numpy arrays can be created using the np.array function

In [5]:
chandigarh = np.array([73,67,43])

In [6]:
weights = np.array([0.3,0.2,0.5])

In [7]:
type(weights)

numpy.ndarray

Just like lists, Numpy arrays support the indexing notation

In [8]:
weights[0]

0.3

## Operating on Numpy Arrays

`np.dot()`

In [9]:
np.dot(chandigarh,weights)

56.8

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [11]:
arr1 * arr2 

array([ 4, 10, 18])

In [12]:
arr2.sum()

15

In [13]:
(chandigarh * weights).sum()

56.8

Numpy Operations are implemented internally using C++, which makes them faster than using python statements & loops which are interpreted at run time

%%time- cal time to run the cell

In [14]:
%%time 
result = 0
for i in range(100000):
    result += i

CPU times: total: 0 ns
Wall time: 4.15 ms


### Multi-Dimensional Numpy Arrays

can represent the climate data for all the regions using a single ***2-dimensional Numpy array.***

In [15]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [16]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [17]:
# 2D array (matrix)
climate_data.shape

(5, 3)

In [18]:
# 1D array (vector)
weights.shape

(3,)

In [19]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [20]:
arr3.shape

(2, 2, 3)

`.dtype` property

In [21]:
weights.dtype

dtype('float64')

In [22]:
climate_data.dtype

dtype('int32')

In [23]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [24]:
weights

array([0.3, 0.2, 0.5])

In [25]:
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [26]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [27]:
climate_data = np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [28]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [29]:
climate_data.shape

(10000, 3)

In [30]:
weights

array([0.3, 0.2, 0.5])

In [31]:
yields = climate_data @ weights

In [32]:
yields.shape

(10000,)

We can now add the `yields` to `climate_data` as a fourth column using the `np.concatenate`function.

In [33]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [40]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [41]:
np.savetxt('climate_results.txt',climate_results,header='temperature,rainfall,humidity,yeild_apples')